
function Subject_Info = Get_Subject_Info()

                                                                                                  
Subject_prompt={'Subject name (First_Last, no space between first and last names)', ...
    'Session Number (for this subject)', ...
    'gender[male, female]', ...
    'age', ...
    'Left eye sight', ...
    'Right eye sight', ...
    'Other vision info. (e.g., Depth vision normal?)' ...
    'Is the subject naive to the purpose of the experiment?', ...
    'Macular degeneration or control?', ...
    'Any other subject information you like to ask' ...
    };
dialog_title='Give_Subject_Information';
num_lines=1;
Subject_default_answer={'Zhaoping_Li', ...
                        '1', ...
                         'female', ...
                         '53', ...
                         'normal', ...
                         'normal', ...
                         'can see depth vision ', ...
                         'naive', ...
                         'control subject ', ...
                         'Subject in good health '};
info=inputdlg(Subject_prompt,dialog_title,num_lines,Subject_default_answer);
Subject_Info.Name  = info{1};
Subject_Info.SessionNumber = str2num(info{2});
Subject_Info.Gender = info{3};
Subject_Info.Age = str2num(info{4});
Subject_Info.LeftEyeSight = info{5};
Subject_Info.RightEyeSight = info{6};
Subject_Info.OtherVisionInfo = info{7};
Subject_Info.NaiveOrNot= info{8};
Subject_Info.MacularDegenerationOrControl= info{9};
Subject_Info.otherInfo= info{10};

